export enum ActionType {
    GET_PRODUCTS = 'GET_PRODUCTS',
    CLEAR_CART = 'CLEAR_CART',
    REMOVE = "REMOVE",
    INCREASE = 'INCREASE',
    DECREASE = 'DECREASE',
    CALCULATE_TOTALS = 'CALCULATE_TOTALS',
}

export enum ActionTypeModal {
    OPEN_MODAL = 'OPEN_MODAL',
    CANCEL = 'CANCEL',
    CONFIRM = 'CONFIRM',
}