#!/bin/bash
# Author: Spyros Tomaras
# Date: 13/07/2023
# Description: This script will ping multiple remote hosts and notify
# Modified: 13/07/2023

hosts="/home/user/professional-scripts/myhosts"

for ip in $(cat $hosts)

do
	ping -c1 $ip &> /dev/null
	if [ $? -eq 0  ]
	then 
	echo $ip is OK
	else 
	echo $ip is NOT OK
	fi
done	
